services:
  - type: web
    name: telegram-expense-bot
    runtime: docker
    plan: free
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ALLOWED_TELEGRAM_USER_ID
        sync: false
      - key: APP_TIME_ZONE
        value: Asia/Phnom_Penh
